name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

env:
  CARGO_TERM_COLOR: always

jobs:
  # コード品質チェック
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libgtk-3-dev \
          libwebkit2gtk-4.1-dev \
          libayatana-appindicator3-dev \
          librsvg2-dev \
          libsoup-3.0-dev \
          libjavascriptcoregtk-4.1-dev
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy
    - name: Rust format check
      run: cargo fmt --check
      working-directory: src-tauri
    - name: Rust lint check
      run: cargo clippy -- -W warnings
      working-directory: src-tauri
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: ESLint check
      run: npm run lint --if-present

  # テスト実行
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libgtk-3-dev \
          libwebkit2gtk-4.1-dev \
          libayatana-appindicator3-dev \
          librsvg2-dev \
          libsoup-3.0-dev \
          libjavascriptcoregtk-4.1-dev
    - uses: dtolnay/rust-toolchain@stable
      with:
        targets: x86_64-pc-windows-gnu
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Run Rust tests
      run: cargo test --verbose
      working-directory: src-tauri
    - name: Run frontend tests
      run: npm test --if-present

  # ビルドテスト
  build-test:
    name: Build Test (Windows Cross-compile)
    runs-on: ubuntu-latest
    needs: [code-quality, test]
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        targets: x86_64-pc-windows-gnu
    - name: Install cross-compilation tools
      run: |
        sudo apt-get update
        sudo apt-get install -y mingw-w64 gcc-mingw-w64-x86-64
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Build application
      run: npx tauri build --target x86_64-pc-windows-gnu

  # リリースビルド
  release:
    name: Release Build (Windows Cross-compile)
    runs-on: ubuntu-latest
    needs: build-test
    if: github.event_name == 'release'
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        targets: x86_64-pc-windows-gnu
    - name: Install cross-compilation tools
      run: |
        sudo apt-get update
        sudo apt-get install -y mingw-w64 gcc-mingw-w64-x86-64
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Build application for release
      run: npx tauri build --target x86_64-pc-windows-gnu
    - name: Upload release assets
      uses: actions/upload-artifact@v4
      with:
        name: booth-organizer-windows
        path: |
          src-tauri/target/x86_64-pc-windows-gnu/release/*.exe
          src-tauri/target/x86_64-pc-windows-gnu/release/bundle/nsis/*.exe


  # デプロイメント
  deploy:
    name: Deploy Release
    runs-on: ubuntu-latest
    needs: release
    if: github.event_name == 'release'
    steps:
    - uses: actions/checkout@v4
    - name: Download all artifacts
      uses: actions/download-artifact@v4
    - name: Display structure of downloaded files
      run: ls -la
    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          booth-organizer-windows/*.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

